doc-warnings: no
test-warnings: no
strictness: medium
max-line-length: 120
autodetect: yes
ignore-paths:
    - doc
    - playground
    - pele/gui
    - examples/gui
ignore-patterns:
    - .*cythonize.py.*
    - ^.*__init__.py.*$
