from _base_regression_graph import BaseRegressionGraph
from single_logistic_regression_potential import LogisticRegressionPotential
from double_logistic_regression_potential import DoubleLogisticRegressionPotential